modLoader="javafml"
loaderVersion="[40,)"
license="GUN GPL v3.0"
[[mods]]
modId="skyland"
version="${file.jarVersion}"
displayName="Skyland"
authors="DubheStudio"
description='''
Skyland Mod
'''
[[dependencies.skyland]]
   modId="forge"
   mandatory=true
   versionRange="[40,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.skyland]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.18.2,1.19)"
   ordering="NONE"
   side="BOTH"
